### ISSUE TITLE
Stopped working since December 8th

### ISSUE THREAD

**Issue by SW1FT** [EchoDev/TwitchHTML5#1]
Video player stays black when you try to load a stream.
I'm using Firefox Developer Edition 44.0a2 (latest build) on Windows 10.

**Comment by EchoDev** [comment]
It seems there is no videostream for HTML5 anymore. I will need to look into it. Anyone here with Chrome who can test it out if it is working?

**Comment by KovuTheHusky** [comment]
Getting the same issue on Chrome.

**Comment by EchoDev** [comment]
The HTML5 stream is back. If you uninstalled the script just re-install it again and it will work again.

**Comment by SW1FT** [comment]
Still not working on my end.

**Comment by EchoDev** [comment]
Are you sure? Did you try reinstalling greasemonkey and the script? Sometimes you have to refresh a page when you first view it. I have been watching without issues for 3 days.

What OS and browser (exact version) are you using?

**Comment by KovuTheHusky** [comment]
Works fine for me! Re-enabled it as soon as I saw your comment three days ago.

**Comment by SW1FT** [comment]
It's working again, kinda weird behavior. It was working, then it stopped and now it's working again after I've disabled/re-enabled Greasemonkey.

**Comment by EchoDev** [comment]
@KovuTheHusky thanks for the info

@SW1FT Good, if you encounter a problem check the console log and post it here or send a private message to me.

The HTML5 player depends completely on Twitch supplying a valid video stream, which is the reason it stopped working for a while. I will be closing this ticket for now.
