### ISSUE TITLE
[solved] Iframe/html5-page stuck in forever-loading / connecting

### ISSUE THREAD

**Issue by onetimesignup** [EchoDev/TwitchHTML5#16]
I noticed this just now on one of the streams and not long after the stream started to lag, desync and burp, the iframe doesn't seem to be the main culprit as I experienced the same issue when I went directly to the html5 page.

To be clear, the video loads just fine but the browser displays the connecting animation on the tab or if you're on the html5 page, loading in the addressfield.

Ive had these issues with other pages that tries to load in some scummy ads or process disqus data in the background, if I was experienced enough with javascript I would add something that stops page-loading after x amount of seconds to prevent this kind of behavior, who knows maybe it fixes the issues with the desync crap as well.

**Comment by onetimesignup** [comment]
update: someone else confirm this; infinitive load, lag, stuttering just as the streamer starts broadcasting.

**Comment by EchoDev** [comment]
Have you been able to find the exact cause of your problem? I never had any infinite load issues, do you have Flash installed? Any other addons that might cause this problem?

**Comment by onetimesignup** [comment]
Happens with or without flash installed but I'm gonna completely remove flash again to make sure.

I'm able to reproduce it by entering the stream of someone whose partnered (or anyone has quality options?) just as the stream has started (less than 10minutes into the stream)

So far ive been getting it every time ive joined to watch `twitch.tv/chickenpoodlesoup`
And it just seems that the html5 player has issues establishing a connection or something.

**Comment by EchoDev** [comment]
Can you check in the Network tab (F12) if Firefox tries to load anything. Maybe that can help figure out what is wrong.

**Comment by onetimesignup** [comment]
just had it on `twitch.tv/kreyg` and I'm not sure if I could make much sense of the network-stuff but it seemed like the player was doing multiple attempts to a xml on spade.twitch.tv  before it calmed down, everything else seemed to move along as normal.

**Comment by EchoDev** [comment]
spade.twitch.tv is a host used for tracking afaik. Are you blocking any trackers/ads? For some time I noticed Twitch going crazy with the trackers and ads. I get over 2k blocked items within a short time.

**Comment by onetimesignup** [comment]
I'm using ad and tracker-blocking software but there's no way im gonna be on the interwebs without it, again what works for me is just refreshing the stream and stop the page-loader just as it's loading in the html5 iframe, wouldnt it be possible to use the script to stop spade to load if it's this that's causing this ?

or are you recommending me to swap to ublock ?

**Comment by EchoDev** [comment]
IMO uBlock **Origin** (Make sure it is the Origin one) is the best adblocker there is. It's highly customizable, has support for loads of blocking lists, uses very little CPU and RAM, and is actively developed. 

See here for more info: https://github.com/gorhill/uBlock
I have been using uBlock for months and never had any issues on Twitch.

**Comment by onetimesignup** [comment]
You were correct, with ublock origin the streamwindow havent been spazzing out anywhere near as much as it did before also this tool hits 200% or more over my main tool.

Your average user may not be using this tool though so eventhough it's solved for me the majority may still experience lags and stuttering and crap so maybe at least consider adding some form of garbage block.

but yea, solved.

**Comment by EchoDev** [comment]
Good to hear. IMO if people want to block ads and trackers uBlock Origin is the way to go. 

I will be closing this ticket. If anyone else has the same problem they can open a new ticket.

**Comment by onetimesignup** [comment]
Damn it, I have to take this back.

I just joined `http://www.twitch.tv/chickenpoodlesoup` and he's glitching and burping and derping and lagging ublock origin has blocked 201 elements and it keeps ticking up every like 5mins or so

**Comment by EchoDev** [comment]
Maybe you can try to ping the videostream server to see if you have a laggy connections.
