### ISSUE TITLE
Select quality 

### ISSUE THREAD

**Issue by Kylllyk** [EchoDev/TwitchHTML5#18]
Hello,

Would it be possible to use the quality selected in the menu?

I'm not a dev but for example in the iframe.attr:

`"src": "http://player.twitch.tv/?branding=false&html5&quality="+$(".js-quality")[0].value+"&showInfo=false&channel=" + $(location).attr('pathname'),`

And reloading on select change:
`$(".js-quality")[0].change(function() {
     html5();
});`

The switch quality works fine but with that I have a bug : I need to click on "pause" button after the switch to start video.

Thanks.

**Comment by onetimesignup** [comment]
I borrowed the `$(".js-quality")[0].value` and it works as long as you jump from medium quality to source but if you switch to anything else and I have to refresh the window.

Yea i have the pause/play bug as well but this is still a awesome feature/fix, thank you for sharing it!

**Comment by EchoDev** [comment]
For me the quality selections already works as is for the most part 

source to high, medium, low or mobile works after a pause and play. The other way around it doesn't work. The player has some issues resuming playback. Especially noticeable when a stream drops frames, it just goes black but in the background the browser keeps downloading the video and audio files (which can be seen in the console, I'm assuming it is downloading correctly). Not sure if anything can be done about it.

**Comment by Viasept** [comment]
Btw in the twitch html5 player source quality is actually chunked, so you should replace source with that.

**Comment by EchoDev** [comment]
If you open the console it already gets the files from chunked even if you select source. Source = chunked for HTML5 player. Please correct me if I'm wrong.

**Comment by Viasept** [comment]
Hmm your correct, just tried with a new firefox and it defaults to chunked. i should probably do a refresh of the other profile

**Comment by EchoDev** [comment]
Closing this, I'm pretty sure changing quality from highest to lowest works fine but going the other way around bugs out, something related to the decoders which also have issues with recovering from glitches in stream.
