### ISSUE TITLE
Black screen (stopped working)

### ISSUE THREAD

**Issue by moozaad** [EchoDev/TwitchHTML5#2]
I just get a black screen. Stopped working a few days ago. FF42. Disabling and reverting to flash still works. I looked in the console but saw nothing related (only wss and emote issues).

The statistics page reports:
Read_state: have_nothing
network_state: network_loading

**Comment by EchoDev** [comment]
This issue is a duplicate of https://github.com/EchoDev/TwitchHTML5/issues/1
