### ISSUE TITLE
No Video: HTTP mixed content gets blocked

### ISSUE THREAD

**Issue by azizLIGHT** [EchoDev/TwitchHTML5#21]
I think Twitch went HTTPS but the streams are on HTTP, so Firefox blocks it for security reasons. Here is what the Console says: 

> 01:11:58.128 Blocked loading mixed active content "http://video-edge-7e9470.mia02.hls.ttvnw.net/hls-835d08/summit1g_20207904672_418125736/chunked/py-index-live.m3u8?token=id=4578084533531189290,bid=20207904672,exp=1458105114,node=video-edge-7e9470-1.mia02.hls.justin.tv,nname=video-edge-7e9470.mia02,fmt=chunked&sig=1ceee9628cb1f9b723b6d5a056fb1b7dd00ee7ed"1 3.462fd40833fb8553550d.js line 1 > eval:1:76582

I've managed to workaround this by installing [this addon](https://addons.mozilla.org/en-US/firefox/addon/toggle-mixed-active-content/?src=ss) that lets me toggle the blocking of mixed active content. When I disable the blocking, the twitch stream loads fine in HTML5 with your userscript. Ideally I'd like to watch Twitch without that addon, as it is easy to forget toggling it back

**Comment by onetimesignup** [comment]
it's what we're all using atm (installation steps has also been updated to cover it).
https may even be the last thing twitch implement before the html5 player goes live

**Comment by EchoDev** [comment]
This ^

**Comment by Rotzbua** [comment]
You do not need this addon.
Click left on the addressbar on the lock, at the infopopup on the right arrow and then deactivate protection for this site.

**Comment by onetimesignup** [comment]
yup you are correct, works for latest firefox v45.0.1

I was clearly too lazy to find it on my own so thanks for sharing :)

**Comment by azizLIGHT** [comment]
You guys are right, the latest Firefox 45 has the option to disable protection for the site. Don't need this addon anymore. Thanks!
