### ISSUE TITLE
[object MediaError]

### ISSUE THREAD

**Issue by azizLIGHT** [EchoDev/TwitchHTML5#22]
The video loads OK in the beginning but then blacks out and shows [object MediaError] after some time, ranging from seconds to minutes.

Stream where I'm having the problem: https://www.twitch.tv/ultra
pastebin of console: https://gist.github.com/azizLIGHT/892b6fbae3e241cfcade

**Comment by EchoDev** [comment]
Works fine for me. Try clearing your cache and restarting your browser.

**Comment by EchoDev** [comment]
This is related to Twitch servers being wonky. I noticed some streamers have constant drops while others have 0 problems. Because the HTML5 player is unable to restart the stream a refresh is needed. Nothing we can do about.
