### ISSUE TITLE
Chrome : no video even with unsafe scripts enabled.

### ISSUE THREAD

**Issue by IlluminaBlade** [EchoDev/TwitchHTML5#25]
I've attempted every sort of browser restart and plugin reloading I can personally think of.
Chrome version 50.0.2661.49 beta-m (64-bit) with Better Twitch TV and Adguard Adblocker.

**Comment by onetimesignup** [comment]
I seem to have issues with v49.0.2623.108 m as well
Worked fine with v46 until i updated

**Comment by EchoDev** [comment]
Seems like this is a problem Chrome devs were aware of for a long time. Nothing for us to do other than wait for new builds with the fix built in.

**Comment by onetimesignup** [comment]
@IlluminaBlade Launch chrome with `--allow-running-insecure-content` by for instance updating the execution path inside the shortcut to look like `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-running-insecure-content`
but use at your own risk

**Comment by IlluminaBlade** [comment]
That launch command does work, but I do feel its a little unsafe to be running around with that so I hope google hurries up.

**Comment by EchoDev** [comment]
It's not per-se unsafe if you watch the address bar. If you are on a site that you need to be 100% safe make sure the address bar is green. When you are on a site with mixed content it should show as yellow. So sites like Gmail, banking sites etc. need to be green.

And I mean, imo you ALWAYS need to check the address bar anyways.

**Comment by onetimesignup** [comment]
does anyone have the 'shield' icon after updating to latest version of chrome?
in the bug-report i linked to the last message was

> Comment 61 by est...@chromium.org, Apr 1, 2016
Status: Fixed

but i still cant seem to be able to run the script normally / shield
