### ISSUE TITLE
Video Quality setting not working

### ISSUE THREAD

**Issue by vibrasphere** [EchoDev/TwitchHTML5#27]
Plays stream as Source by default, if you click any other quality it stops the stream and loads for infinite time. (the cog icon)

Firefox 45.0.1 Win8x64, flash npapi uninstalled.
-------------------------
Also some visual glitches on twitch web address in the url bar:
![capture](https://cloud.githubusercontent.com/assets/5372918/14114249/f4d9d162-f5de-11e5-8fe8-0f4efbad0da9.JPG)

No disrespect, but unusable, have to reinstall flash back, since Source quality with Greasemonkey, etc. eats a lot of CPU, I get spikes that even moving mouse lags, which doesn't while on flash. Also both the script and/or flash version of Twitch eat up same amount of approx. 400mb of ram.

**Comment by vibrasphere** [comment]
OK, it does switch quality, but it doesn't resume the play, so you need to click the Play icon to play the new quality of the stream, meanwhile the cog icon is still annoyingly spinning non-stop.

Switching from Source to Medium drops RAM usage by ~100MB

**Comment by vibrasphere** [comment]
Ok after 1 hour of Twitch firefox.exe CPU 30%. I'm dun.

**Comment by EchoDev** [comment]
Ok bye

**Comment by onetimesignup** [comment]
@vibrasphere the quality select IS semi-broken, half the times it doesn't switch resolutions or it tries to and completely freezes the player (play/pause does nothing)

solution/trick when it breaks: rightclick on the iframe/player -> This frame -> Reload Frame

for me this iframe/load situation doesn't pull more than 3-10% in firefox if I only have twitch+github open.
besides 'greasemonkey+script' im also running 'stylish', 'ghostery' and ublock origin.

flash completely murdered firefox and w7 for me (freezelags, crashes),
no way in f-ing hell im going back to that garbage.

if you're not happy with this solution or flash then you can try out 'Livestreamer' / VLC / mpc
