### ISSUE TITLE
does not work on archived videos

### ISSUE THREAD

**Issue by enatividad** [EchoDev/TwitchHTML5#29]
or at the least, it does not work on this url:
https://www.twitch.tv/demolition_d/v/55261792

**Comment by onetimesignup** [comment]
twitch isnt supporting html5 for their vods, yet.

**Comment by enatividad** [comment]
oh, I am sorry, I am not aware.

since the issue is server-side, should we close the issue for now? perhaps we should.

**Comment by mixxan** [comment]
Merely making a note here in case someone with more knowledge in the area want to check it out, there's a definitive chance i'm utterly and absolutely wrong here. 

I can without a problem watch vods using html5 (with their popup player and forcing the video type using url parameter, ie &html5), and i don't have flash installed either (have made very sure of this). And as a final note at a quick glance the page source seems to correspond fairly well to a html5 video too.

**Comment by onetimesignup** [comment]
I think you're unintenionally fooling yourself.
If the url contains `&channel=StreamerName` then it will be trying to start the livestream, not the vod.

To play vods using the external player the link needs to look like `https://player.twitch.tv/?html5&video=VIDEONUMBERSGOESHERE` which currently doesn't run, at least not on firefox.

**Comment by enatividad** [comment]
https://player.twitch.tv/?html5&video=v55261792 the link seemed to work in this form, ty. that being said though, the featureset is really limited

**Comment by EchoDev** [comment]
Hmm yeah that seems to work. I will give it a look and see if I can fix it quick.

**Comment by onetimesignup** [comment]
I remember finding a youtube video that had a description linking to a video with the `player.twitch.tv` and using a time= argument, that was however for the flash player but we might be able to tap into this with javascript if the player actually supports the argument for html5 and then use it to skip, I'm still trying to find the video, it was about some hearthstone tactic.

**Comment by EchoDev** [comment]
Hmm I got the script working but the VOD streams died for me. Anyone else having the same problem?

**Comment by onetimesignup** [comment]
still working here, dont forget that mixed content block crap, gota disable it for every vod.

**Comment by EchoDev** [comment]
@onetimesignup Yeah I forgot to add the "v" to the video stream link 

@enatividad thanks for making us aware of the VOD support

Script has been updated, enjoy the VOD support!

**Comment by EchoDev** [comment]
Also is it me or are HTML5 VODs not muted?

**Comment by onetimesignup** [comment]
should they be muted ?

**Comment by EchoDev** [comment]
Muted as in muted when there is copyrighted music playing. I get the warning from Twitch but the audio still plays. In Flash it would be muted.

**Comment by onetimesignup** [comment]
you still have audio for some segments of the vods, only the parts where the twitch script/bot noticed any copyrighted music will be removed

**Comment by EchoDev** [comment]
Yeah but for example: https://www.twitch.tv/witwix/v/58260374

He is playing music but it is not muted. I thought Twitch was pretty strict when it comes to muting?

**Comment by onetimesignup** [comment]
If you open it in flash you can see three small red lines in video where the sound has been ripped out, and since we cannot jump in the html5 vod player its gonna take you a solid 45mins to reach the first removed chunk.

**Comment by enatividad** [comment]
@EchoDev wow you work fast, ty. by the way, what do you mean about not muted?

if you are talking about if the vod is mutable, it is mutable.
