### ISSUE TITLE
stopped working 4/8/16?

### ISSUE THREAD

**Issue by tqphan** [EchoDev/TwitchHTML5#30]
only shows the first frame for me. can anyone else confirm?

**Comment by EchoDev** [comment]
It's probably on Twitch's end, even forcing autoplay with autoplay=true in the link doesn't work.

**Comment by onetimesignup** [comment]
>‏@TwitchSupport: We are currently investigating the cause of error code 0x30220001 for many users on the Xbox One app. ^DM

> ‏@TwitchSupport: Previous Xbox One issues (error code 0x30220001) should now be resolved. Thanks for your patience. :) ^DM

the broken "autoplay" for html5 is now working again
