### ISSUE TITLE
Autoplay is not working

### ISSUE THREAD

**Issue by PRoosta** [EchoDev/TwitchHTML5#31]
Currently on Firefox autoplay does not work on twitch pages (incl. streams) and you have to press the play button for it to begin playing.

I believe this is due to a recent change in the twitch html5 player but confirmation by other users would be nice. 
While this isn't a major issue it would be nice if autoplay could be added back somehow.

**Comment by onetimesignup** [comment]
https://github.com/EchoDev/TwitchHTML5/issues/30

@EchoDev  maybe you should just keep these issues open/visible and just add (unsolvable) or (confirmed) to the title

**Comment by EchoDev** [comment]
@onetimesignup done >:)

I might be able to fix this but I will have to look into it. Not sure tho, I might be limited by javascript.

**Comment by YoDevil** [comment]
I can confirm this behaviour, if it can be anyhow helpful ;)

**Comment by EchoDev** [comment]
Seems to be working again.

**Comment by onetimesignup** [comment]
and just like that they added it again
