### ISSUE TITLE
VODs broken due to blocked cross-origin requests

### ISSUE THREAD

**Issue by EchoDev** [EchoDev/TwitchHTML5#32]

**Comment by EchoDev** [comment]
Could possibly be fixed by disabling yet another security feature, might be time to find a proper fix or replace the complete HTML5 player with a different player so we have more control.

**Comment by EchoDev** [comment]
Working again, for now.

**Comment by onetimesignup** [comment]
it just seems super unstable and wonky, been experiencing issues with it ever since i found it, usually latest videos work semi-ok while older videos either dont run at all or are a big page-refresh pain in the butt- the later seems to be effecting latest/recent videos as well, i always think vods are broken but after turning off protection and refreshing like 3-4 times and having super patience it eventually boots up

**Comment by EchoDev** [comment]
I think it has partially to do with the HTML5 player not being able to recover from glitches/lag.

I notice that when I watch streamers who occasionally drop frames it helps alot to let the player buffer for a few seconds at the start of a stream so it has time to recover when streamer lag frames/glitch. If it would be possible to detect the player stopping playback I would be able to force reload it  but I haven't found a way to detect it.

**Comment by onetimesignup** [comment]
`$('span.play-button.js-play-button').click();`
but
>hurr durr i'm inside a iframe hurr durr good luck

**Comment by EchoDev** [comment]
I'm actually thinking of replacing the Twitch player with Clappr
https://github.com/clappr/clappr

I might upload a experimental version to this Github so people can test and give some feedback. Replacing the player with Clappr will give me a lot more control.

**Comment by onetimesignup** [comment]
ive never heard of this, and i cant seem to find anything which points it to being supported with twitch,
if you get it working and offers you the tools you need then go for it!

**Comment by EchoDev** [comment]
Twitch doesn't have to support it. You just feed it the m3u8 playlist file and it will play it. I use Clappr on another site and I used the same method.
