### ISSUE TITLE
Faded Colors

### ISSUE THREAD

**Issue by M4dDan** [EchoDev/TwitchHTML5#33]
hi, i'm using this script about few days, its very nice for the cpu load while watching streams, i have just a question, the colors of the stream seems a bit faded respect the flash version, it's normal? there is a way to render the stream less faded?

**Comment by M4dDan** [comment]
i did a screenshot 
left side its normal view , right side its with TwitchHTML5
http://i.imgur.com/oixP4gi.jpg

**Comment by GXTX** [comment]
What browser do you use and do you notice it anywhere else?

**Comment by M4dDan** [comment]
i use firefox... if i disable greasemonkey + TwitchHTML5 , i can see the stream like the left side, if i re-enable it seems like right side, in other browser like chrome i just see like left side

**Comment by GXTX** [comment]
![nodiff](https://cloud.githubusercontent.com/assets/858612/14611191/ff122910-055e-11e6-8a81-ad9c497f1f4a.png)
idk I'm not seeing it.

**Comment by M4dDan** [comment]
then idk too where is the problem seems really strange , i'm not pretty sure but ur screen its a bit colorless , but the red fish and the purple seems a bit different in their color. XD

**Comment by onetimesignup** [comment]
if you use the direct link to the html5 player you will be able to tell if its the script or just twitch html5 support

`https://player.twitch.tv/?html5&showInfo=false&channel=` followed by streamer name in lowercase

**Comment by M4dDan** [comment]
oh nice, then seem to be an html5 issue, same problem with the direct player and greasemonkey disabled

**Comment by Eisys** [comment]
Do you have an Nvidia GPU?
This could be caused by this Nvidia Control panel setting:
http://i.imgur.com/vRxAYx7.png

Or a similar setting in AMD's equivalent.

The 0-255 means normal colors. 16-235 means 'faded' colors.
I had this problem a long time ago on youtube and this was the only way to fix it. Originally the 'with the video player settings' setting was chosen.

**Comment by EchoDev** [comment]
It could also be related to messed up encoding settings on Twitch's end. If you could capture raw output from the Flash player you could compare it to the HTML5 player (HTML5 player can be captured easily)

**Comment by M4dDan** [comment]
@Eisys 

yes i have nvidia and ur soulution has worked ! But i haven't this problem in other sites like youtube , was only for twitch, and in nvidia panel before i had the first choice selected (video player settings)

then can be a problem with html5 player in twitch but with nvidia panel u can solve it 

Thank you anyway.

**Comment by fireattack** [comment]
@M4dDan Under certain setup (in my case, Win 7 (D3D9?) + Firefox or Chrome + DVI cable), this problem can happen on Youtube actually, but only in HD videos.

You can try this video without the work around mentioned by eisys:

https://www.youtube.com/watch?v=BZQ7Va3gAdE

(make sure you watch it in 1080p60)

In the first few seconds, it shows an Word document. the background of the paper should be pure white (255,255,255) but if I didn't modify that settings manually it would show as grey.

Also check: https://bugs.chromium.org/p/chromium/issues/detail?id=333619#c98

It has been a while, so I am not sure if it's fixed or not. And your setup may not be able to reproduce that as well.

**Comment by EchoDev** [comment]
Added to FAQ:

https://github.com/EchoDev/TwitchHTML5/wiki
