### ISSUE TITLE
HTTP and HTTPS

### ISSUE THREAD

**Issue by ImpalaPUA** [EchoDev/TwitchHTML5#35]
I'm using **Chrome 50.0.2661.94** (I will use lifecoach's stream because I don't mind giving him ad money from disabling all my add ons)

## With the script disabled in Tampermonkey:

If I visit **HTTP://**player.twitch.tv/?channel=Lifecoach1981&html5=1
-Everything works fine

If I visit **HTTPS://**player.twitch.tv/?channel=Lifecoach1981&html5=1
-The buttons for twitch display, but no video plays: https://imgur.com/vCJVZjQ

## With the script ENABLED in Tampermonkey:

The same applies above.

However, when I visit https://www.twitch.tv/Lifecoach1981 (notice the HTTPS), I get the same issue of watching the player with HTTPS. Meaning I see the twitch display (https://imgur.com/vCJVZjQ) but nothing plays

I tried to switch to http://www.twitch.tv/Lifecoach1981 , but it forces HTTPS, so at the moment, I can't watch twitch with chat in HTML5. I would have to visit the player.twitch.tv but that defeats the purpose of having this script in tampermonkey

Fix would be appreciated

**Comment by EchoDev** [comment]
You need to disable the mixed content protection.

see https://github.com/EchoDev/TwitchHTML5/issues/25#issuecomment-203863037

**Comment by ImpalaPUA** [comment]
Thanks, that fixed it
