### ISSUE TITLE
installation tutorial

### ISSUE THREAD

**Issue by hobnob11** [EchoDev/TwitchHTML5#36]
i was debugging it for like half an hour as to why it wasnt working then i realised the second plugin you install that blocks content or something needs to be "red", by defualt its green and it looks like its supposed to be like that.

might want to update the installation instructions to mention that, otherwise amazing script! its time flash was a thing of the past.

**Comment by EchoDev** [comment]
I don't think I completely understand. Could you show me a picture?

Also are we talking about Chrome or Firefox?

**Comment by EchoDev** [comment]
I added pictures to the installation instructions for Firefox, since Chrome seems to be broken I did not add pictures for it. 

https://github.com/EchoDev/TwitchHTML5/wiki
