### ISSUE TITLE
Heads Up: Frozen Player due to missing 'start watching' button caused by a uo Filter

### ISSUE THREAD

**Issue by onetimesignup** [EchoDev/TwitchHTML5#38]
inside the uBlock Origin 'Fanboy’s Enhanced Tracking List‎' there's a block-rule `##.player-overlay` preventing the mature-streamer popup ->
>The broadcaster indicated that the channel is intended for mature audiences.
>[ Start Watching ]

from being displayed, and you need to press/accept this popup in order to resume the stream playback for these kinds of streams.

**Comment by EchoDev** [comment]
This should be fixable by adding 

`www.twitch.tv##.player-overlay`

to the whitelist inside uBlockOrigin

**Comment by onetimesignup** [comment]
bah, i was trying to fix this one as well but entered `player.twitch.tv##@#.player-overlay` and nothing happened.

nope, still not working for me, lemme restart firefox

**Comment by EchoDev** [comment]
Guess this is fixed >:)
