### ISSUE TITLE
Not working on VODs

### ISSUE THREAD

**Issue by YoDevil** [EchoDev/TwitchHTML5#39]
Everytime I have to disable the script and reload the page to be able to play VODs. Since you probably can't fix the player, would it be possible to filter out VODs to disable the script on those urls only?

**Comment by EchoDev** [comment]
You can add this under the include line in the script and it should skip VODs
If you care you can make a proper exclude with regex but this should work too

```
// @exclude https://www.twitch.tv/*/v/*
// @exclude https://twitch.tv/*/v/*
```


I thought VODs were working with the script but something must have broke

**Comment by YoDevil** [comment]
Oh sorry, I just realized the problem only affects links with ?t=XXhYYmZZs GET request.
Anyways, excluding that is not working, and i never really understood regex LUL

**Comment by EchoDev** [comment]
Huh, thats weird. 
Do you have a VOD link for me that doesn't work with it?

**Comment by YoDevil** [comment]
Here's what i have at my fingertips right now https://www.twitch.tv/ognglobal/v/67698546?t=01h14m36s

**Comment by YoDevil** [comment]
It won't autoplay, nor jump to the specified time

**Comment by EchoDev** [comment]
Hmm I see what the problem is.

The script gets the video ID from the url. When you add a timestamp to it, the script makes the timestamp part of the video ID and thus fails. I should be able to fix that soon. As for jumping to specified times, I don't think Twitch has implemented that yet in their VOD HTML5 player and I don't think I'm able to implement it since seeking doesn't seem to work at all.

**Comment by YoDevil** [comment]
Ah i get it, makes sense.
So, can you try to make up a regex to exclude VODs while we wait for Twitch to implement that function?

**Comment by EchoDev** [comment]
The excludes lines work fine for me.

Anyways, I fixed the timestamp in URL issue
https://github.com/EchoDev/TwitchHTML5/commit/d80f824e2b343788a9dc8fe0b2c3c2891acd94b1

Seeking still does not work tho, all VODs will start from the beginning.

**Comment by YoDevil** [comment]
Whoops you're right, i don't know what i did the first time i tried to exclude it :/
Thanks!
