### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by pendo324** [EchoDev/TwitchHTML5#4]
Sometimes the video will slow down and get out of sync and then speed up to catch back up to the audio. No idea why this would happen

**Comment by EchoDev** [comment]
This is probably related to having a slow pc. What are your pc specs? HTML5 player will be more heavy than flash since flash uses (better) GPU acceleration.

**Comment by pendo324** [comment]
Intel Core i7-2600 CPU @ 3.40GHz
NVIDIA GeForce GTX 960
8 GB of RAM

**Comment by EchoDev** [comment]
Hmm, that should be no problem.

What OS/Browser/connection speed do you have?

**Comment by SW1FT** [comment]
This also happens to me sometimes and it's due to my unstable connection.

**Comment by EchoDev** [comment]
Thanks @SW1FT 
To be sure it's a problem on user-end and not script related I will need more info from @pendo324

**Comment by EchoDev** [comment]
This is most likely an issue on Twitch.tv's end or a problem with decoder. Not something that can be fixed with this script.
