### ISSUE TITLE
Theater mode button gets cut because of BetterTTV

### ISSUE THREAD

**Issue by SW1FT** [EchoDev/TwitchHTML5#6]
Firefox 45.0a2, Win10, but it probably happens with every browser/OS that has the BetterTTV add-on.

Here's a screenshot:
![bug](https://cloud.githubusercontent.com/assets/6627739/12598969/b5ea5fec-c485-11e5-84d8-74b7f6ad1887.png)

**Comment by EchoDev** [comment]
Looks like there is not enough space for all the buttons. Is shortened the text of the button

https://github.com/EchoDev/TwitchHTML5/commit/7d0ef1b8ea6c7f42863ec3389383bf52f9467084
