### ISSUE TITLE
VoD Support?

### ISSUE THREAD

**Issue by m157** [EchoDev/TwitchHTML5#7]
I watch a lot of VoDs on twitch, would it be possible to make those work with html5?

**Comment by SW1FT** [comment]
Not yet as record labels are forcing Twitch and other websites (such as Spotify, Soundcloud) to use Flash based DRM protection.

**Comment by EchoDev** [comment]
There is no backstream for VODs to be used. The HTML5 player uses a backstream that Twitch supplies.

No supply = no workie.

If Twitch supplies HTML5 streams for the VODs I will take a look at it.
