### ISSUE TITLE
Impossible to change quality

### ISSUE THREAD

**Issue by Tiferod** [EchoDev/TwitchHTML5#9]
I tried both on Firefox (44) and Chrome (48), and i can't change the quality of the stream, i'm stuck on Source. If i try, the stream just freezes. Is this intended ?

**Comment by EchoDev** [comment]
Looks to be an issue on Twitch.tv's end. The player doesn't seem to handle change in quality well. You can set the default quality in the script on line 17 where it says &quality=source to whatever you want (source, high, low or mobile should work)

**Comment by Tiferod** [comment]
Ok, too bad. And thanks for the trick, it works well.
